extrinsics:
  T_base_camera:
  - - -0.33674
    - 0.54922
    - -0.76483
    - 0.0
  - - 0.87646
    - -0.11404
    - -0.46777
    - 0.0
  - - -0.34413
    - -0.82786
    - -0.44297
    - 0.0
  - - 0.0
    - 0.0
    - 0.0
    - 1.0
  calibrated: axes_user
  note: 快速方向标定（用户视角三步手势）- 相对跟随已校准
